//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardGame_v2Entities : DbContext
    {
        public CardGame_v2Entities()
            : base("name=CardGame_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblCard> tblCard { get; set; }
        public virtual DbSet<tblCardPack> tblCardPack { get; set; }
        public virtual DbSet<tblCardType> tblCardType { get; set; }
        public virtual DbSet<tblDeck> tblDeck { get; set; }
        public virtual DbSet<tblDeckCard> tblDeckCard { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserCardCollection> tblUserCardCollection { get; set; }
        public virtual DbSet<tblUserRole> tblUserRole { get; set; }
        public virtual DbSet<tblVirtualPurchase> tblVirtualPurchase { get; set; }
    }
}
