//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCard()
        {
            this.tblDeckCard = new HashSet<tblDeckCard>();
            this.tblUserCardCollection = new HashSet<tblUserCardCollection>();
        }
    
        public int idCard { get; set; }
        public string cardname { get; set; }
        public int manacost { get; set; }
        public int attack { get; set; }
        public int life { get; set; }
        public Nullable<int> fkCardType { get; set; }
        public byte[] cardimage { get; set; }
    
        public virtual tblCardType tblCardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeckCard> tblDeckCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserCardCollection> tblUserCardCollection { get; set; }
    }
}
