//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCardCollection
    {
        public int fkUser { get; set; }
        public int fkCard { get; set; }
        public int numcards { get; set; }
    
        public virtual tblCard tblCard { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
