//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVirtualPurchase
    {
        public int idVirtualPurchase { get; set; }
        public int fkUser { get; set; }
        public int fkCardPack { get; set; }
        public System.DateTime timeofpurchase { get; set; }
        public int numpacks { get; set; }
    
        public virtual tblCardPack tblCardPack { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
