//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVirtualPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVirtualPurchase()
        {
            this.tblUserCardCollection = new HashSet<tblUserCardCollection>();
        }
    
        public int idVirtualPurchase { get; set; }
        public int fkUser { get; set; }
        public int fkCardPack { get; set; }
        public System.DateTime timeofpurchase { get; set; }
        public int numpacks { get; set; }
    
        public virtual tblCardPack tblCardPack { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserCardCollection> tblUserCardCollection { get; set; }
    }
}
